/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentAlertsRouteImport } from './routes/parent.alerts'
import { Route as ParentAttendanceRouteImport } from './routes/parent.attendance'
import { Route as ParentProgressRouteImport } from './routes/parent.progress'
import { Route as ParentResultsRouteImport } from './routes/parent.results'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentClassRouteImport } from './routes/student.class'
import { Route as StudentExploreRouteImport } from './routes/student.explore'
import { Route as StudentHomeworkRouteImport } from './routes/student.homework'
import { Route as StudentPracticeRouteImport } from './routes/student.practice'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAnnouncementsRouteImport } from './routes/teacher.announcements'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher.homework'
import { Route as TeacherQuizzesRouteImport } from './routes/teacher.quizzes'
import { Route as StudentNotesIndexRouteImport } from './routes/student.notes.index'
import { Route as StudentNotesIdRouteImport } from './routes/student.notes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAlertsRoute = ParentAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAttendanceRoute = ParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentRoute,
} as any)
const ParentProgressRoute = ParentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ParentRoute,
} as any)
const ParentResultsRoute = ParentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => ParentRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentClassRoute = StudentClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExploreRoute = StudentExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHomeworkRoute = StudentHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPracticeRoute = StudentPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnnouncementsRoute = TeacherAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherQuizzesRoute = TeacherQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentNotesIndexRoute = StudentNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotesIdRoute = StudentNotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/parent/alerts': typeof ParentAlertsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/results': typeof ParentResultsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/class': typeof StudentClassRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/notes/$id': typeof StudentNotesIdRoute
  '/student/notes/': typeof StudentNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/parent/alerts': typeof ParentAlertsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/results': typeof ParentResultsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/class': typeof StudentClassRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/notes/$id': typeof StudentNotesIdRoute
  '/student/notes': typeof StudentNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/parent/alerts': typeof ParentAlertsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/results': typeof ParentResultsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/class': typeof StudentClassRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/practice': typeof StudentPracticeRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/quizzes': typeof TeacherQuizzesRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/notes/$id': typeof StudentNotesIdRoute
  '/student/notes/': typeof StudentNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/parent'
    | '/register'
    | '/student'
    | '/teacher'
    | '/parent/alerts'
    | '/parent/attendance'
    | '/parent/progress'
    | '/parent/results'
    | '/student/attendance'
    | '/student/class'
    | '/student/explore'
    | '/student/homework'
    | '/student/practice'
    | '/student/profile'
    | '/student/progress'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/teacher/homework'
    | '/teacher/quizzes'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/student/notes/$id'
    | '/student/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/parent/alerts'
    | '/parent/attendance'
    | '/parent/progress'
    | '/parent/results'
    | '/student/attendance'
    | '/student/class'
    | '/student/explore'
    | '/student/homework'
    | '/student/practice'
    | '/student/profile'
    | '/student/progress'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/teacher/homework'
    | '/teacher/quizzes'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/student/notes/$id'
    | '/student/notes'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/parent'
    | '/register'
    | '/student'
    | '/teacher'
    | '/parent/alerts'
    | '/parent/attendance'
    | '/parent/progress'
    | '/parent/results'
    | '/student/attendance'
    | '/student/class'
    | '/student/explore'
    | '/student/homework'
    | '/student/practice'
    | '/student/profile'
    | '/student/progress'
    | '/teacher/announcements'
    | '/teacher/attendance'
    | '/teacher/homework'
    | '/teacher/quizzes'
    | '/parent/'
    | '/student/'
    | '/teacher/'
    | '/student/notes/$id'
    | '/student/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/alerts': {
      id: '/parent/alerts'
      path: '/alerts'
      fullPath: '/parent/alerts'
      preLoaderRoute: typeof ParentAlertsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/attendance': {
      id: '/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentAttendanceRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/progress': {
      id: '/parent/progress'
      path: '/progress'
      fullPath: '/parent/progress'
      preLoaderRoute: typeof ParentProgressRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/results': {
      id: '/parent/results'
      path: '/results'
      fullPath: '/parent/results'
      preLoaderRoute: typeof ParentResultsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/class': {
      id: '/student/class'
      path: '/class'
      fullPath: '/student/class'
      preLoaderRoute: typeof StudentClassRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/explore': {
      id: '/student/explore'
      path: '/explore'
      fullPath: '/student/explore'
      preLoaderRoute: typeof StudentExploreRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/homework': {
      id: '/student/homework'
      path: '/homework'
      fullPath: '/student/homework'
      preLoaderRoute: typeof StudentHomeworkRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/practice': {
      id: '/student/practice'
      path: '/practice'
      fullPath: '/student/practice'
      preLoaderRoute: typeof StudentPracticeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/announcements': {
      id: '/teacher/announcements'
      path: '/announcements'
      fullPath: '/teacher/announcements'
      preLoaderRoute: typeof TeacherAnnouncementsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/quizzes': {
      id: '/teacher/quizzes'
      path: '/quizzes'
      fullPath: '/teacher/quizzes'
      preLoaderRoute: typeof TeacherQuizzesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/notes/': {
      id: '/student/notes/'
      path: '/notes'
      fullPath: '/student/notes/'
      preLoaderRoute: typeof StudentNotesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notes/$id': {
      id: '/student/notes/$id'
      path: '/notes/$id'
      fullPath: '/student/notes/$id'
      preLoaderRoute: typeof StudentNotesIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface ParentRouteChildren {
  ParentAlertsRoute: typeof ParentAlertsRoute
  ParentAttendanceRoute: typeof ParentAttendanceRoute
  ParentProgressRoute: typeof ParentProgressRoute
  ParentResultsRoute: typeof ParentResultsRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAlertsRoute: ParentAlertsRoute,
  ParentAttendanceRoute: ParentAttendanceRoute,
  ParentProgressRoute: ParentProgressRoute,
  ParentResultsRoute: ParentResultsRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentClassRoute: typeof StudentClassRoute
  StudentExploreRoute: typeof StudentExploreRoute
  StudentHomeworkRoute: typeof StudentHomeworkRoute
  StudentPracticeRoute: typeof StudentPracticeRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentNotesIdRoute: typeof StudentNotesIdRoute
  StudentNotesIndexRoute: typeof StudentNotesIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentClassRoute: StudentClassRoute,
  StudentExploreRoute: StudentExploreRoute,
  StudentHomeworkRoute: StudentHomeworkRoute,
  StudentPracticeRoute: StudentPracticeRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentNotesIdRoute: StudentNotesIdRoute,
  StudentNotesIndexRoute: StudentNotesIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAnnouncementsRoute: typeof TeacherAnnouncementsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherHomeworkRoute: typeof TeacherHomeworkRoute
  TeacherQuizzesRoute: typeof TeacherQuizzesRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnnouncementsRoute: TeacherAnnouncementsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherHomeworkRoute: TeacherHomeworkRoute,
  TeacherQuizzesRoute: TeacherQuizzesRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
